workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.orangehrm.mobile"
      node: 18.16.0
      java: 17
    scripts:
      - name: Install npm dependencies (skip peer deps)
        script: |
          npm install --legacy-peer-deps
      - name: Build release APK (unsigned)
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk

