workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.orangehrm.mobile"
      node: 18.16.0
      java: 17
      android: sdk
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set up Android project
        script: |
          cd android
          ./gradlew clean
      - name: Build debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
