workflows:
  android-apk:
    name: Build Android APK
    environment:
      flutter: stable
    scripts:
      - cd mobile_client
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - mobile_client/build/app/outputs/flutter-apk/app-debug.apk
