workflows:
  android-apk:
    name: Build Android APK
    environment:
      flutter: stable
    working_directory: mobile_client
    scripts:
      - flutter pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
